### ISSUE TITLE
A video can be reported multiple times (indefinitely) in quick succession by the same user

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#1]
Preconditions:
1. RegretsReporter is installed

Steps to reproduce:
1. Access YouTube and click on any video you want to report
2. Report the selected video by completing both steps of the process (initial report and sending additional info)
3. Close the “Thank you for your submission.” pop-up either by using the “X” button in the upper right corner or by clicking outside the pop-up.
4. Without refreshing the page repeat steps 2 & 3.
5. Notice that the video can be reported again, and as many times as the user desires (indefinitely)

Expected results:
In order to avoid abuse:
1. A unique user should be able to only report a certain video once
OR
2. Reporting the same video multiple times should be gated behind a cooldown period i.e. a certain amount of time must pass until a user can report the same video once more

Actual results:
Following the normal reporting process, without refreshing the page, a video can be reported multiple times (indefinitely) by the same user.

Affected versions:

Firefox
- Nightly 82.0a1/20200903151816
- Beta 81.0b6/20200903205131
- Release 80.0.1/20200831163820
Google Chrome
- Chrome 85.0.4183.83

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS
- macOS 10.15

NOTE: Due to currently being in the process of verifying that the add-on does indeed send usage stats every 24 hours, I cannot restart my system to access another OS. Will update the issue with other tested OSes once I can safely confirm that stats are indeed sent every 24 hours. 

The attachment shows the entries for the same video, which was reported in quick succession.
![2020-09-04_10h16_09](https://user-images.githubusercontent.com/50236075/92212532-c7a3da80-ee9a-11ea-89b4-ffe9aeeba744.png)

**Comment by motin** [comment]
These are good UX suggestions, and something we will consider for updates in the future, thanks! Currently, however, we are fine with filtering excessive reports per user/video during analysis.
I will re-open this issue when/if we choose to include it in a future update.
