### ISSUE TITLE
fake logout

### ISSUE THREAD

**Issue by icf20** [mozilla-extensions/regrets-reporter#10]
on vivaldi 3.3.2022.47  if user is login on youtube and goes to youtube home page and by clicking the youtube logo or goes to a channel it gets "logout" this is undone by simply making ctrl+f5 and the user gets login on youtube again

is extremely annoying

**Comment by motin** [comment]
Thanks for your report! Indeed, we have confirmed that there is a conflict with certain user features, including this kind of strange logged in/out appearances on Chromium browsers. Reported already as https://github.com/mozilla-extensions/regrets-reporter/issues/9 and a fix will be released shortly.
