### ISSUE TITLE
White string “Testing Frontend” on white background on app main page 

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#103]
Description:
After accessing http://94.3.209.235:8502/  (QA app) and reaching the app main page, clicking and dragging the mouse cursor on the top part of the page reveals that the white string “Testing Frontend” is present there. The string is invisible due to it being white on a white background.

Changing the theme to dark from the Streamlit’s settings reveals the string.

The main app is also affected by this.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Once on the main page, click on the page and while keeping the mouse button pressed, drag the cursor around the page
3. Notice the white string “Testing Frontend” on the white background

Actual:
The white string “Testing Frontend” on the white background of the app’s main page is not visible.

Expected:
The string’s color should be changed so it’s visible on the white background.

https://user-images.githubusercontent.com/50236075/163186589-1d87f139-80cc-4648-bdda-1396dc9c4e78.mp4

**Comment by iRanadheer** [comment]
Done. please check.

**Comment by acornestean** [comment]
Verified fixed on the latest version of the app.

The “Testing Frontend” string is now black and visible on the white background.

![2022-04-18_11h41_25](https://user-images.githubusercontent.com/50236075/163782431-4ad04c20-9522-4d90-9a8a-e226afe0c85a.png)
