### ISSUE TITLE
Apply the same treatment to the user signup form as in issue #81

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#105]
Description:
When signing up for a new user, after inputting the username, clicking anywhere on the page content will submit the username and proceed to the next field – password.

This is basically the same issue as described in #81.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. From the “User Management” pane, select “Signup” from the drop down list.
3. Input the username in the field and click anywhere on the page
4. Notice the username is submitted and the password field appears.
5. Repeat Step 3 for the password field
6. Notice the password is submitted by clicking on the page

Actual:
Username/Password can be submitted by clicking on the page content.

Expected:
The same form style used for #81 should be used here as well.

https://user-images.githubusercontent.com/50236075/163382234-d6aa8566-54c0-494e-823c-658dc63d97a1.mp4

**Comment by iRanadheer** [comment]
Please check now

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

All fields are exposed from the beginning of the sign up process and creating a new account is possible, as expected.
