### ISSUE TITLE
“User already exists” error after creating a new account

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#106]
Description:
After filling in the sign up form for a new account and submitting the credentials, the app proceeds with the account creation and announces the user that the account is getting set up. Once this process is completed, a notification is displayed letting the user know that the account has been set up and it’s ready to log in.
Immediately after this, the app displays a warning message that the user already exists and the UI looks like the first step of the account creation process i.e. the username field is displayed and the app asks the user to choose a username.

At this point, the user will still be able to log in using the newly created account and get redirected to the “Labeling” section of the app.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Sign up for an account
3. Once the credentials are submitted and the account is created, notice the app will display a green success message stating that the account has been set up
4. Notice that immediately after the previous success message was displayed, a warning message is displayed stating that the user already exists.
5. Log in using the previously created account and get redirected to the “Labeling” section

Actual:
Immediately after successfully creating an account, a warning is displayed stating that the user already exists, however the credentials can be used to successfully log in.

Expected:
The warning message stating that the user already exists should not be displayed for newly created users under the conditions that the account username does not already exist.

https://user-images.githubusercontent.com/50236075/163548493-5b5a19ea-2af5-478f-b939-7793a2ce14aa.mp4

**Comment by iRanadheer** [comment]
Fixed, please check!

**Comment by acornestean** [comment]
@iRanadheer 

Cannot verify on the latest version of the QA app due to issue #110.

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

With issue #110 fixed, the sign up form is properly displayed and the signing up process can be completed without issues. After completing the signing up process, the “user already exists” error is no longer displayed.
