### ISSUE TITLE
Error when submitting a recommendation on both admin or regular accounts

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#107]
Description:
The recommendation submission process fails and an error is displayed.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Log in either as admin or a regular user
3. Go to the “Labeling” section (or get redirected to the section when using a regular account)
4. Submit a recommendation
5. Notice the submission fails with an error

Actual:
Recommendation submission fails and an error is displayed.

Expected:
The recommendation submission process should succeed and not throw an error.

https://user-images.githubusercontent.com/50236075/163551853-a310aad3-84ab-4709-a0f2-38da27eb355d.mp4

**Comment by iRanadheer** [comment]
Thanks, Alex,

Fixed

**Comment by acornestean** [comment]
@iRanadheer 

Cannot verify on the latest version of the QA app due to issue #109.

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

With issue #109 fixed, the Labeling UI properly loads and recommendation submissions can be performed on both admin and regular accounts without any errors occurring.
