### ISSUE TITLE
Can log in using the wrong/no password

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#108]
Description:
Currently I am able to log in using an existing username and any random string of characters as password OR no password at all (i.e. left the password field empty).

This applies to both admin and regular accounts.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. From the sidebar drop down list, select “Login”
3. Enter the username and:
- a. any random string of characters for a password
- b. leave the password field empty
4. Click on the “Login” button
5. Notice the user gets logged in

Actual:
Users can log in using the correct username BUT either the wrong/random/no password.

Expected:
Users should be able to log in by using only the correct username and the password associated for that account instead of a wrong/random/no password.

https://user-images.githubusercontent.com/50236075/163557386-e4c19fb8-e3fb-4bb0-b995-386e3975771f.mp4

**Comment by iRanadheer** [comment]
Oh! This is a serious bug. Many thanks, @acornestean! I've fixed it, please check again.

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

Users are now required to enter the correct valid password in order to log in.

Users are no longer able to log in using an invalid password or to not enter anything in the password field. 
A warning message is displayed upon attempting to log in using an incorrect password or leaving the field empty - "Please enter the correct username/password".

![2022-04-18_12h16_51](https://user-images.githubusercontent.com/50236075/163787232-71ece196-8595-4434-9a98-b3bf97122a5d.png)

![2022-04-18_12h17_13](https://user-images.githubusercontent.com/50236075/163787251-4ab2937b-8283-442a-9442-eb656bd8a781.png)
