### ISSUE TITLE
“FileNotFoundError: [Errno 2] No such file or directory: '.streamlit/settings.json'” ERROR when accessing Labeling

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#109]
Description:
After logging in and reaching the “Labeling” section, an error is thrown, preventing the recommendation submission process.

Both admin and regular accounts are affected.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Log in
3. Reach the “Labeling” section
4. Notice an error is displayed and the recommendation submission process is unavailable.

Actual:
After reaching the “Labeling” section, an error is displayed which prevents the recommendation submission process.

Expected:
The Labeling section UI should load and allow users to submit recommendations.

![2022-04-18_12h45_40](https://user-images.githubusercontent.com/50236075/163790653-abd3b40a-3aa2-4209-bade-0fb9b9487939.png)

![2022-04-18_12h45_43](https://user-images.githubusercontent.com/50236075/163790659-d8ce7035-83a8-487f-a733-2b8c95ba61dd.png)

**Comment by iRanadheer** [comment]
Hey,

Please check now.

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

The error is no longer displayed when accessing Labeling on either admin or regular accounts.

The UI properly loads and recommendation submissions can be performed.
