### ISSUE TITLE
[Chrome] Searches are not registered when user is signed in to YouTube

### ISSUE THREAD

**Issue by motin** [mozilla-extensions/regrets-reporter#11]
It is important to be able to classify a recommendation as stemming from search vs non-search. However, when being logged in, some search-based navigations are not showing up in the history to report.

**Comment by motin** [comment]
Probably fix committed in https://github.com/mozilla-extensions/regrets-reporter/commit/6c10f4e6d6730bdb2a356f1449d38b20de55ee29

**Comment by acornestean** [comment]
Verified the fix with add-on version 1.0.1 on Chrome (85.0.4183.121), Firefox Unbranded Beta (82.0b2/20200922183749) and Firefox Unbranded Release (81.0/20200917005511) under Windows 10 Pro 64-bit and Ubuntu 16.04 LTS.

On both Chrome and Firefox, search based navigations are properly registered in the history to report, while the user is signed in to YouTube.
