### ISSUE TITLE
“FileNotFoundError: [Errno 2] No such file or directory: '.streamlit/profile_dict.pk'” ERROR when signing up for an account

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#110]
Description:
Attempting to sign up for an account throws an error, preventing the process.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Select “Signup” from the sidebar
3. Notice an error is displayed preventing the sign up process

Actual:
An error is thrown when selecting the “Signup” operation to create a new account.

Expected:
Users should be able to sign up for new accounts.

![2022-04-18_12h48_25](https://user-images.githubusercontent.com/50236075/163791508-99775b00-7e12-4e11-baed-9de802856af6.png)

**Comment by iRanadheer** [comment]
Hey, Can you check now?

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

The error is no longer displayed when selecting “Signup” from the sidebar, the sign up form being properly displayed and the signing up process proceeding without issues.
