### ISSUE TITLE
“FileNotFoundError: [Errno 2] No such file or directory: '.streamlit/profile_dict.pk'” ERROR when accessing “Users Management”

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#112]
Description:
Accessing “Users Management” as an admin throws an error and does not load the corresponding UI.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Log in with an admin account
3. Select “Users Management” operation from the sidebar
4. Notice an error is displayed

Actual:
An error is displayed when accessing “Users Management” as an admin.

Expected:
The “Users Management” UI should load without issues and not throw an error.

![2022-04-18_13h11_18](https://user-images.githubusercontent.com/50236075/163793770-aee4204d-5b8a-4e4b-be13-b2bf65ac4df8.png)

**Comment by iRanadheer** [comment]
Hey,

Please check now

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

Accessing “Users Management” section as admin will now properly display the user management UI and the error is no longer displayed.
