### ISSUE TITLE
Error displayed when changing the sampling mode in “Assign Data” section

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#113]
Description:
An error is displayed after selecting the desired sampling mode from the “Assign Data” section. 

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Log in with an admin account
3. Select “Assign Data” operation from the sidebar
4. Once at the “Assign Data” section, select a sampling mode
5. Notice an error is displayed

Actual:
An error is displayed when selecting a sampling mode from the “Assign Data” section.

Expected:
Users should be able to change the sampling mode without the app throwing an error.

https://user-images.githubusercontent.com/50236075/163794388-582c7eca-44bb-49a7-aa8d-144dd55ccca4.mp4

**Comment by iRanadheer** [comment]
Hey, 

Please check now.

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

Selecting/Changing the sampling mode will no longer display the error.
