### ISSUE TITLE
Remove RRUMPredictDatasetArrow

### ISSUE THREAD

**Issue by jmccrosky** [mozilla-extensions/regrets-reporter#126]
We probably don't need RRUMPredictDatasetArrow and can just use RRUMDatasetArrow for all cases.

**Comment by aapot** [comment]
As commented in https://github.com/mozilla-extensions/regrets-reporter/pull/125 I'd wrap our train, validation and test datasets into Lightning DataModule and then we could try this: https://pytorch-lightning.readthedocs.io/en/stable/common/evaluation.html#testing

**Comment by aapot** [comment]
Solved for now at https://github.com/mozilla-extensions/regrets-reporter/pull/132
