### ISSUE TITLE
[Critical][Chrome] Usage stats are not registered on Chrome

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#4]
Preconditions:
1. RegretsReporter is installed

Steps to reproduce:
1. Access YouTube and browse videos (directly click on videos from the home page, search for and access videos, click on recommended videos from video watch pages)
2. Access the add-on’s debug console
3. Run the following commands:
- await openWpmPacketHandler.navigationBatchPreprocessor.processQueue();
- await youTubeUsageStatistics.summarizeUpdate();
4. Notice that usage stats are not registered i.e usage stats are zeroed
5. Restart the browser
6. Go to the add-on’s options page and click on “Inspect Collected Data”
7. Go to the “YouTube Usage Statistics” tab

Note: The restart from step 5 forced collected data to be sent and thus can now be inspected in the “YouTube Usage Statistics” tab

8. Click on the “Click to show” button of the last entry
9. Notice that usage stats are not registered/ are zeroed

Expected results:
Usage stats should be registered by the extension on Chrome

Actual results:
Usage stats are zeroed/not registered

Affected versions:

Google Chrome
- Chrome 85.0.4183.102

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS
- macOS 10.15

**Comment by acornestean** [comment]
Please note that after some time, usage stats appeared in both the debug console via commands and also in the “YouTube Usage Statistics” tab

**Comment by acornestean** [comment]
Additional info: Yesterday everything worked as expected

**Comment by motin** [comment]
This has been fixed by https://github.com/mozilla-extensions/regrets-reporter/commit/3cd575b4cbd63e24a150596ab772412289878f4d since it resulted in the xpath helper method not to be available, which in turn is necessary for the ui instrument to work, which in turn is what supplies data to the usage stats. 
Fix will be included in v0.9.8.

**Comment by motin** [comment]
These are my experiences testing v0.9.8 with the above fix:

1. Install the add-on
2. Access the add-on’s debug console
3. Run the following commands:
- await openWpmPacketHandler.navigationBatchPreprocessor.processQueue();
- await youTubeUsageStatistics.summarizeUpdate();
4. Notice that usage stats are not registered i.e usage stats are zeroed
5. Access YouTube and browse videos (directly click on videos from the home page, search for and access videos, click on recommended videos from video watch pages)
6. Access the add-on’s debug console
7. Run the following commands:
- await openWpmPacketHandler.navigationBatchPreprocessor.processQueue();
- await youTubeUsageStatistics.summarizeUpdate();
8. Access the add-on’s debug console
9. Notice that usage stats are properly registered

**Comment by motin** [comment]
Update: After chatting with with @acornestean, we found that this only happens when the source code has been minimized, eg not in development builds.

**Comment by acornestean** [comment]
Verified the fix with add-on version 0.9.9 on Chrome (85.0.4183.102), Beta Developer Edition (81.0b9/20200910180444) and Unbranded Release (80.0.1/20200831163820) under Windows 10 Pro 64-bit and Ubuntu 16.04 LTS.

Usage stats (watch time, watch page loads via direct access, recommendations or search) are now properly registered on Chrome.

On Firefox, usage stats are registered correctly, as before.
