### ISSUE TITLE
[Critical][Chrome] Extension pop-up shows current reported video and history only after refresh on Chrome

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#5]
Preconditions:
1. RegretsReporter is installed

Steps to reproduce:
1. Access YouTube and click on a video
2. Click on the add-on icon in the toolbar to report the video
3. Notice that the pop-up displays a message stating to either wait for the YT page to load or to reload the page
4. Close the pop-up
5. Refresh the page
6. Click on the add-on icon in the toolbar to report the video
7. Notice that the pop-up now properly displays the data of the reported video (thumbnail, title, etc)
8. Click on another video from the right panel
9. Click on the add-on icon in the toolbar to report the video
10. Notice that the pop-up still displays the previous video data
11. Refresh the page
12. Click on the add-on icon in the toolbar to report the video
13. Notice that the pop-up now properly displays the data of the reported video

Expected results:
The add-on should properly refresh the data according to the current video. Also, it should register the YT browsing history accordingly.

Actual results:
Without refreshing the page/video, the data the add-on shows in the UI is not accurate/reflect the current reported video/current history.

Affected versions:

Google Chrome
- Chrome 85.0.4183.102

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS
- macOS 10.15

The screenshot shows that the add-on pop-up displays a different video from the current one which is watched. Also the history is blank, which is not accurate as I navigated to the current watched video from the one showed in the pop-up.

![2020-09-11_11h07_32](https://user-images.githubusercontent.com/50236075/92890825-25e33700-f420-11ea-9f1e-37ffba2dc368.png)

**Comment by acornestean** [comment]
Additional info: Yesterday everything worked as expected

**Comment by motin** [comment]
This is indeed something that appears intermittently. Works most of the time but sometimes not. I made some changes related to internal messages being lost intermittently (d5f8f63bcf6ff3ac0daf3a050ffce0eef72732c5) and one about intermittent false negatives when matching response bodies (ce25cfc1a127b33ee8389486a16c928032b61378). Also, 9bdb0af0c48ae55dfdaab654f6e8f19cc8a9a339 may be helpful here. Altogether, this ought to fix this issue and when testing briefly manually it seems to be working consistently.

**Comment by motin** [comment]
This is my experience in Chrome using v0.9.8 (with the above mentioned fixes):

1. Access YouTube and click on a video
2. Click on the add-on icon in the toolbar to report the video
3. **The pop-up properly displays the data of the reported video**
4. Close the pop-up

Then:

1. Refresh the page
2. Click on the add-on icon in the toolbar to report the video
3. Notice that the pop-up properly displays the data of the reported video (thumbnail, title, etc)
4. Click on another video from the right panel
5. Click on the add-on icon in the toolbar to report the video
6. **The pop-up properly displays the data of the reported video**

Then:

1. Refresh the page
2. Click on the add-on icon in the toolbar to report the video
3. **The pop-up properly displays the data of the reported video**

**Comment by motin** [comment]
Update: After chatting with with @acornestean, we found that this only happens when the source code has been minimized, eg not in development builds.

**Comment by acornestean** [comment]
Verified the fix with add-on version 0.9.9 on Chrome (85.0.4183.102), Firefox Beta Developer Edition (81.0b9/20200910180444) and Firefox Unbranded Release (80.0.1/20200831163820) under Windows 10 Pro 64-bit and Ubuntu 16.04 LTS.

On both Chrome and Firefox, the add-on properly updates the pop-up information to match the currently reported video and the current browsing history. Refreshing is no longer necessary for the panel to display the correct info.
