### ISSUE TITLE
Extension breaks YouTube Shorts on desktop

### ISSUE THREAD

**Issue by mustafa-git** [mozilla-extensions/regrets-reporter#59]
Link shows YouTube Shorts with and without the extension enabled:
https://imgur.com/a/UA3erMr

**Comment by jmccrosky** [comment]
I can't reproduce.  Can you share browser, browser version, and RegretsReporter version?

**Comment by mustafa-git** [comment]
Browser: Mozilla Firefox 97.0.1(64-bit) (flatpak package on Debian 11)
Regrets reporter version: 2.0.6

**Comment by rowanlovejoy** [comment]
I'm experiencing the same issue. There is a dark overlay over all YouTube Shorts videos, exactly as shown in @mustafa-git's screenshots. Disabling Regrets Reporter and refreshing the page immediately resolves the problem. I've provided my own below screenshots showing a YouTube short with and without RegretsReporter enabled (first and second screenshot, respectively).

Browser: `Firefox 98.0.1 (64-bit)`
RegretsReporter version: `2.0.6`
OS: `Windows 10 Pro 64-bit version 21H2`

![image](https://user-images.githubusercontent.com/44379649/159118380-23944a63-e8c0-4831-b382-5c090c71c135.png)
![image](https://user-images.githubusercontent.com/44379649/159118403-16a94d78-f3fd-4344-b545-43277729ce82.png)

**Comment by jmccrosky** [comment]
Can you provide a URL and/or explain how you get to that screen?  It looks like a mobile page, but you are on a desktop browser I assume.

**Comment by jmccrosky** [comment]
Thanks!  We've got some limited developer capacity right now, but I'll do my best to find a way to get this fixed.

**Comment by rowanlovejoy** [comment]
Thanks. Let me know if you need any more information.
