### ISSUE TITLE
Narrowing the browser window causes display issues on the onboarding page

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#7]
Preconditions:
1. RegretsReporter is installed
2. The onboarding page is opened in a tab

Steps to reproduce:
1. Go to the onboarding page
2. Adjust the size of the browser window to be as narrow as possible vertically
3. Notice that part of the “Reporting a "YouTube Regret" It’s easy! Just follow these 3 steps.” string will get lower on the page and become invisible on the white background
4. Scroll down the page
5. Notice overlapping text in the "3 Steps" section

Expected results:
Text on the onboarding page should be visible, readable and not display overlapping regardless of the size of the browser window.

Actual results:
The text on the onboarding page is not properly visible when narrowing the browser window.

Affected versions:
Firefox
- Unbranded Release (80.0.1/20200831163820)
- Beta Developer Edition (81.0b9/20200910180444)

Google Chrome
- Chrome 85.0.4183.102

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS
- macOS 10.15

![regretsreporter](https://user-images.githubusercontent.com/50236075/93214311-af22a280-f76d-11ea-884f-2444b3530a94.gif)

**Comment by motin** [comment]
Thanks for the report :) We decided not to implement responsive design aspects, given it is a desktop only page. Closing since this is out of scope for v1.0
