### ISSUE TITLE
Username/Password submission and logging in can be done by clicking anywhere on the page content

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#81]
Description:
When inputting the username, a tooltip states to “Press Enter to apply” to advance to the next field – the password field. Although pressing Enter does work, so does simply clicking outside the field, anywhere within the page content.
After inputting the password, clicking anywhere on the page will also proceed with the logging in process, without the user having to click on “Submit”.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Click on the “User Management” menu
3. From the drop down, select “Login”
4. Click on “Authorization”
5. Input the username
6. Do not press Enter, but instead click anywhere on the page
7. Notice the username is accepted and the authorization process proceeds to the next step – inputting the password-protected
8. Input the password
9. Do not press Enter, but instead click anywhere on the page
10. Notice the password is accepted and the user is logged in

Expected:
The authorization process should proceed only when submitting credentials via pressing Enter and finally the user should get logged in only after clicking the “Submit” button.

Actual:
The authorization process can proceed by simply inputting the credentials and clicking anywhere on the page content.
Users can then log in (after inputting the credentials) without clicking on the “Submit” button.

https://user-images.githubusercontent.com/50236075/161047293-2accb933-f1f0-49bb-a628-bb605c06dcec.mp4

**Comment by iRanadheer** [comment]
Hey Alex,

You are right, the submit button is just a dummy. Streamlit executes as soon as you interact with any of its widgets, except those widgets are placed inside a form. We can change it to streamlit forms if it helps.

**Comment by jmccrosky** [comment]
The form might be a better UX Ranu, if you have time?

**Comment by acornestean** [comment]
Verified fixed on the latest version of the app.

1. Both username and password fields are displayed from the get go now after selecting Login from the sidebar. The expandable "Authorization" panel previously containing the two fields is no longer displayed, which streamlined the logging in flow.
2. After inputting either the username or password, clicking on the page no longer submits the credentials and thus no longer logs the user in automatically, by accident.
3. No unwanted logging in until the user clicks on the Login button.

https://user-images.githubusercontent.com/50236075/163180700-08b9028d-abaf-41be-858c-8ecc42b86cac.mp4
