### ISSUE TITLE
Users are not kept logged in after reloading the page

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#82]
Description:
After logging in, reloading the page will log the user out. The entire logging in process will have to be repeated afterwards.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Log in
3. Reload the page
4. Notice you got logged out

Expected:
Reloading the page should keep the user logged in.
Actual:
Reloading the page will log out the user.

https://user-images.githubusercontent.com/50236075/161048187-9136aee3-6902-48fa-b7a3-065503014ba2.mp4

**Comment by iRanadheer** [comment]
We'll have to save cookies to be able to do that. We are still working on that. thanks for bringing it up!

**Comment by iRanadheer** [comment]
Please check now

**Comment by acornestean** [comment]
Verified fixed on the latest version of the QA app.

Reloading the page will keep users logged in now, until they choose to log out via the newly implemented “Log Out” button.
