### ISSUE TITLE
Blank credential fields after logging in as regular user

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#87]
Description:
After logging in as a regular user and getting redirected to the labeling section, in the “Authorization” box from the sidebar, the fields for username and password are blank.

For some reason they appear zoomed in and there is content hidden in those fields as for example, if I Ctrl+A → Ctrl+C in the username field, my username is copied to clipboard.

Furthermore, I’m still able to input text in those fields (which appears to be appended at the end of the already existing, but hidden, contents) and because of issue 81, as soon as I click anywhere on the page contents, the credential submission process is triggered and the app attempts to log me in with the wrong credentials and throws an error: “Sorry, you do not have access to the system. Please write to the admin for access.”

Additionally, after the failed log in, if I correct the incorrect credentials and attempt to log in, I’m logged out.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Sign up for an account
3. After the account has been created, log in. Notice getting redirected to the labeling section of the app.
4. Notice the blank username/password fields in the left sidebar.
5. Input anything in any of the fields and click anywhere on the page content
6. Notice that the app triggers the credential submission process and attempts to log in the user due to issue 81. However, since the credentials have been modified as part of Step 5, the app throws an error: “Sorry, you do not have access to the system. Please write to the admin for access.”
7. Correct the modified credentials so as they are the proper ones used to log in
8. Press Enter or click anywhere on the page
9. Notice the user gets logged out.

Expected:
1. The username/password fields should not accept input after the user logs in.
2. I would suggest changing the “Authorization” box to show a message along the lines of “Logged in as XYZ” and possibly a log out button and not the current implementation.

Actual:
1. Username/password fields appear blank in the left sidebar after logging in as a regular user.
2. Username/password fields still accept input after having logged in and lead to the app throwing “Sorry, you do not have access to the system. Please write to the admin for access.”
3. Correcting the modified credentials and attempting to log in, will actually log out the user

https://user-images.githubusercontent.com/50236075/161248264-b51483ba-22ce-41f3-b2b8-5574103a0f01.mp4

**Comment by iRanadheer** [comment]
Hey, 

That's because we are tweaking the HTML structure of the radio button widgets. Usually, the radio buttons appear vertically, its taking too much space, so we shifted to a horizontal radio widget. We will try to remove that expander the moment the user logged in. Thanks!

**Comment by acornestean** [comment]
Verified fixed on the latest version of the app.

After logging in as either a regular user or admin, the credential fields have content in the form of the username and the hidden password.

![2022-04-13_10h35_59](https://user-images.githubusercontent.com/50236075/163124474-7eb0cf9f-7f48-4a52-acc0-f9005024b4a1.png)

![2022-04-13_10h36_17](https://user-images.githubusercontent.com/50236075/163124499-3f4c923f-a8c1-4939-9b7e-c9091626c111.png)
