### ISSUE TITLE
[Chrome] Conflicts with certain YouTube user features

### ISSUE THREAD

**Issue by motin** [mozilla-extensions/regrets-reporter#9]
Chrome users have reported YouTube breakage via reviews (https://chrome.google.com/webstore/detail/regretsreporter/obpoeflheeknapimliioeoefbfaakefn):

> Breaks use of youtube. When you have it enabled you appear logged-in, and not logged into youtube, at the same time. Impossible to list history, and subscribe to new channels.

> You cant subscribe any channel with regrets reporter enabled

> It is bothersome at times, when you deliberately want to subscribe but can't do so. I had to disable the extension, subscribe, then re-enable.

**Comment by motin** [comment]
Probable fix committed in https://github.com/mozilla-extensions/regrets-reporter/commit/620e31762f89cc22bdfa116964d29bd3594e94c5

**Comment by kangarooo** [comment]
Makes youtube unusable
Cant comment, cant like, cant subscribe. Thouse are broken. How?

**Comment by acornestean** [comment]
Verified the fix with add-on version 1.0.1 on Chrome (85.0.4183.121), Firefox Unbranded Beta (82.0b2/20200922183749) and Firefox Unbranded Release (81.0/20200917005511) under Windows 10 Pro 64-bit and Ubuntu 16.04 LTS.

On both Chrome and Firefox, YouTube functionality is no longer affected/performs as expected. Users are able to properly:
- log in/out
- subscribe/unsubscribe
- turn notifications on/off
- like/dislike a video (liking a video adds it to the liked playlist, disliking/un-liking a video will remove it from the liked playlist)
- comment
- like/dislike/un-like/un-dislike comments
- play/pause videos
- videos appear in YouTube history
