### ISSUE TITLE
“AttributeError” displayed when accessing Labeling section as admin

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#90]
Description:
“AttributeError: st.session_state has no attribute "user_langs". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization” is displayed when accessing the Labeling section after logging in as admin.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Log in as admin
3. Access Labeling from the sidebar
4. Notice the displayed error

Actual:
“AttributeError: st.session_state has no attribute "user_langs". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization” is displayed when accessing the Labeling section after logging in as admin.

Expected:
Labeling functions should be available and not throw the mentioned error.

![2022-04-05_14h27_38](https://user-images.githubusercontent.com/50236075/161745076-bb79be38-5572-4ccf-9c6c-a29d8896b8b4.png)

**Comment by iRanadheer** [comment]
Thanks Alex,

it's fixed now!

**Comment by acornestean** [comment]
Verified fixed on the latest app version. 

The error is no longer shown and proper content is displayed in the Labeling section when logged in as admin.

![2022-04-06_12h26_09](https://user-images.githubusercontent.com/50236075/161944657-9eada6f2-6e9d-489f-8b17-f72cb89b8eac.png)
