### ISSUE TITLE
Unable to choose datapoints and assign RAs in Assign Data section

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#91]
Description:
As per the PRD doc – Assign Data section, in the Assign Data section of the app, admins can choose between 3 methods in which data can be assigned, choose the number of datapoints to assign and select the RAs to whom the datapoints will be assigned. Once done, the “Submit” button should be clicked to process the selections.

In reality:
1. There are only two available methods of assigning data – “Random” and “Active Learning”. “First n rows” method is missing from the dropwdown.
2. After selecting from the available methods of assigning data, the admin has no way of choosing the datapoints to be assigned, nor the RA to whom the datapoints will be assigned.
3. The “Submit” button is missing.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Log in as admin
3. Access “Assign Data” from the sidebar.
4. Once the page loads, open the “Choose the mode of sampling” dropwdown. Notice only 2 methods of data assignment - “Random” and “Active Learning”.
5. Select any of the two methods. Notice there are no further steps/ways to continue the assignment process i.e. choose the datapoints and assign them to RAs. Only some code snippets are displayed. 
6. Notice the “Submit” button is not present (might be due to the assignment process not having reached the last step).

Actual:
1. There are only two available methods of assigning data – “Random” and “Active Learning”. “First n rows” method is missing from the dropwdown.
2. After selecting from the available methods of assigning data, the admin has no way of choosing the datapoints to be assigned, nor the RA to whom the datapoints will be assigned.
3. The “Submit” button is missing.

Expected:
1. Three methods should be available for assigning data - “First n rows”, “Random” and “Active Learning”, as per the PRD doc.
2. Admin users should be able to continue the assignment process i.e. choose the datapoints and assign them to Ras.
3. The “Submit” button should be displayed.

![2022-04-05_14h48_46](https://user-images.githubusercontent.com/50236075/161747564-8e273be9-756a-49c4-a4a4-abcfb52897f1.png)

**Comment by jmccrosky** [comment]
Sorry, desired functionality has changed and this is actually correct.  I updated the PRD.
