### ISSUE TITLE
Can submit a “Bad recommendation” without specifying a reason

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#92]
Description:
Users can label a video as a bad recommendation without specifying a reason – either chosen from the dropdown or mentioned via text box.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Signup for an account or log in using an existing account.
3. Once at the Labeling section, select the “Bad recommendation” radio button and leave any of the other fields empty/ options un-selected i.e. do not specify a reason for marking the video as a bad recommendation.
4. Click on the “Submit” button.
5. Notice the “bad recommendation” submission process proceeds without the user specifying a reason for the video being bad, and a new pair of videos is presented to the user for analysis.

Actual:
Users can label a video as a bad recommendation without specifying a reason – either chosen from the dropdown or mentioned via text box.

Expected:
As per the PRD doc, users should not be able to mark a recommendation as bad without specifying the reason for it – either chosen from the dropdown or mentioned via text box.

https://user-images.githubusercontent.com/50236075/161750015-5d896ef9-4267-4e10-adda-213cce5713f2.mp4

**Comment by jmccrosky** [comment]
Fixed in PR 95 which is under review.

**Comment by iRanadheer** [comment]
The fix is working! Closing this issue, please re-open if you find any issues.

**Comment by acornestean** [comment]
Verified fixed on the latest version of the app.

Users (admin/signed up users) are no longer able to submit a “Bad recommendation” without specifying a reason.

https://user-images.githubusercontent.com/50236075/162687190-bbe1574b-0efc-41f9-a979-2a02b59e64c6.mp4
