### ISSUE TITLE
Cannot submit a bad recommendation by only writing the reason instead of choosing a reason from the drop down

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#97]
Description:
Users are unable to proceed with the bad recommendation submission process if ONLY writing a reason for which the video has been deemed bad and not choosing a reason from the drop down.

Currently, the submission process is successful if:
- the user chooses a reason from the drop down - expected
- the user chooses a reason from the drop down and writes a reason in the text field - expected

The submission process fails if:
- the user does not choose a reason from the drop down – expected
- the user does not choose a reason from the drop down BUT specifies a reason in the text field – not expected, since the wording on the text field tooltip leads me to understand that I can submit a bad recommendation by writing the reason the video is considered bad in case said reason is not found throughout the drop down ones. 

Presumably, the issue is a regression caused by fixing issue #92.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Signup for an account or log in using an existing account.
3. Once at the Labeling section, select the “Bad recommendation” radio button, don’t select anything from the drop down and input a reason in the text field.
4. Click on the “Submit” button.
5. Notice the “bad recommendation” submission process fails if the user does not choose a reason from the drop down.

Actual:
Users are unable to submit a bad recommendation if they only write a reason for which the video was considered bad and not select a reason from the drop down.

Expected:
Users should be able to submit a bad recommendation by only writing a reason for which the video was considered bad, in case the reason cannot be found in the drop down listed ones.

https://user-images.githubusercontent.com/50236075/162687419-4634c220-7e1d-460a-a068-50492f955e1f.mp4

**Comment by jmccrosky** [comment]
Label was inaccurate.  We want to require a reason from the drop-down.  The text field is for comment only.

**Comment by acornestean** [comment]
Verified fixed on the latest version of the app.

With the updated tooltip from #98, it is now clear that a reason is mandatory to be chosen from the drop down in order for the submission process to be carried out and that simply writing a reason in the text field was not enough.

As such, the flow was working as intended even before but now there’s no misunderstanding as to the required steps.
